[tool.poetry]
name = "virtual-bartender"
version = "0.1.0"
description = ""
authors = ["Brett Heinkel <bheinks@gmail.com>"]
readme = "README.md"
packages = [{include = "virtual_bartender"}]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1.4"
django-nested-admin = "^4.0.2"
psycopg2 = "^2.9.5"
djangorestframework = "^3.14.0"
python-decouple = "^3.6"
pillow = "^9.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
