# Generated by Django 4.1.4 on 2022-12-18 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bartender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='settled',
            field=models.BooleanField(default=False, verbose_name='Settled?'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='bartender.order'),
        ),
    ]
