# Generated by Django 4.2.7 on 2024-01-24 21:29

import bartender.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartender', '0002_alter_patron_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='photo',
            field=models.ImageField(blank=True),
        ),
    ]
