# Generated by Django 4.2.7 on 2024-01-24 21:51

import bartender.models
import bartender.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartender', '0003_alter_drink_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='photo',
            field=models.ImageField(blank=True, storage=bartender.storage.OverwriteStorage(), upload_to=bartender.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='patron',
            name='photo',
            field=models.ImageField(blank=True, storage=bartender.storage.OverwriteStorage(), upload_to=bartender.models.get_upload_path),
        ),
    ]
