# Generated by Django 4.1.4 on 2022-12-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartender', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
