# Generated by Django 5.0.1 on 2024-01-27 19:14

import bartender.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartender', '0004_alter_drink_photo_alter_patron_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField()),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
