# Generated by Django 4.1.4 on 2022-12-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bartender', '0007_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='price',
        ),
    ]
