# Generated by Django 5.0.1 on 2024-01-27 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartender', '0007_alter_sound_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
