# Generated by Django 4.1.4 on 2022-12-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartender', '0009_drink_photo_drink_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
