# Generated by Django 4.1.4 on 2022-12-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartender', '0010_alter_drink_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
