# Generated by Django 4.1.4 on 2023-04-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartender', '0012_patron_photo_alter_drink_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='in stock?'),
        ),
    ]
